//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentReport.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncidentReport.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applicant cannot be a suspect.
        /// </summary>
        internal static string ApplicantCannotBeSuspectRuleException {
            get {
                return ResourceManager.GetString("ApplicantCannotBeSuspectRuleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty.
        /// </summary>
        internal static string ApplicationDescriptionCannotBeEmptyException {
            get {
                return ResourceManager.GetString("ApplicationDescriptionCannotBeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description should contain a maximum of {0} characters.
        /// </summary>
        internal static string ApplicationDescriptionTooLongException {
            get {
                return ResourceManager.GetString("ApplicationDescriptionTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description should contain a minimum of {0} characters.
        /// </summary>
        internal static string ApplicationDescriptionTooShortException {
            get {
                return ResourceManager.GetString("ApplicationDescriptionTooShortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty.
        /// </summary>
        internal static string ApplicationTitleCannotBeEmptyException {
            get {
                return ResourceManager.GetString("ApplicationTitleCannotBeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title should contain a maximum of {0} characters.
        /// </summary>
        internal static string ApplicationTitleTooLongException {
            get {
                return ResourceManager.GetString("ApplicationTitleTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title should contain a minimum of {0} characters.
        /// </summary>
        internal static string ApplicationTitleTooShortException {
            get {
                return ResourceManager.GetString("ApplicationTitleTooShortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suspects were indicated.
        /// </summary>
        internal static string NoSuspectsWereIndicatedException {
            get {
                return ResourceManager.GetString("NoSuspectsWereIndicatedException", resourceCulture);
            }
        }
    }
}
